name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  RUSTFLAGS: -D warnings

jobs:
  test:
    name: fmt, clippy, test
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2.9.1

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features --tests -- -D warnings

      - name: cargo test
        run: cargo test --all-targets --all-features

      - name: cargo doc
        run: cargo doc --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
